server:
  port: 18082
spring:
  datasource:
    default:
      url: jdbc:mysql://localhost:3306/dev_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: Xxl010113**
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      url: jdbc:mysql://localhost:3306/dev_uccenter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: Xxl010113**
      driver-class-name: com.mysql.cj.jdbc.Driver
unif:
  rdb:
#    url: jdbc:mysql://localhost:3306/dev_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
#    username: root
#    password: Xxl010113**
#    driver-class-name: com.mysql.cj.jdbc.Driver
    default:
      url: jdbc:mysql://localhost:3306/dev_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: Xxl010113**
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      url: jdbc:mysql://localhost:3306/dev_uccenter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: Xxl010113**
      driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xxl.multipledb.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper:
#  helper-dialect: mysql
#  params: count=countSql
#  reasonable: true
#  support-methods-arguments: true