spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/dev_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    #    username: root
    #    password: Xxl010113**
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    default:
      url: jdbc:mysql://localhost:3306/dev_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: Xxl010113**
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      url: jdbc:mysql://localhost:3306/dev_uccenter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: Xxl010113**
      driver-class-name: com.mysql.cj.jdbc.Driver