server:
  port: 18082
spring:
  datasource:
    db1:
      url: jdbc:mysql://172.20.238.5:33801/dev_uccenter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: uccenter
      password: Unif2022!
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      url: jdbc:mysql://localhost:3306/dev_uccenter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: Xxl010113**
      driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xxl.multipledb.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper:
#  helper-dialect: mysql
#  params: count=countSql
#  reasonable: true
#  support-methods-arguments: true